name: Step

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Enable step debugging
        run: echo "::set-env name=ACTIONS_STEP_DEBUG::true"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: github/docs

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.16'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
