name: Step

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          repository: github/docs

      - name: Set up Go
        env:
          ACTIONS_STEP_DEBUG: true
        uses: actions/setup-go@v5
        with:
          go-version: '1.16'

      - uses: actions/setup-python@v5
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          python-version: '3.10' 
